# Generated by Django 4.2.2 on 2023-07-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermanagement',
            options={'verbose_name': 'User (management)', 'verbose_name_plural': 'Users (management)'},
        ),
        migrations.AlterModelOptions(
            name='usersales',
            options={'verbose_name': 'User (sales)', 'verbose_name_plural': 'Users (sales)'},
        ),
        migrations.AlterModelOptions(
            name='usersupport',
            options={'verbose_name': 'User (support)', 'verbose_name_plural': 'Users (support)'},
        ),
    ]
