# Generated by Django 4.2.2 on 2023-08-20 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('users', '__first__'),
        ('epic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('attendees', models.IntegerField(blank=True)),
                ('event_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='contracts.contract')),
                ('status_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='epic.statusevent')),
                ('users', models.ManyToManyField(related_name='events', to='users.usersupport')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
