# Generated by Django 4.2.2 on 2023-08-20 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        ('clients', '0001_initial'),
        ('epic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True)),
                ('due_date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.client')),
                ('status_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='epic.statuscontract')),
                ('users', models.ManyToManyField(related_name='contracts', to='users.usersales')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
    ]
