# Generated by Django 4.2.5 on 2023-10-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='users',
            field=models.ManyToManyField(related_name='contracts', to='users.usersales'),
        ),
    ]
