# Generated by Django 4.2.2 on 2023-06-26 21:57

from django.db import migrations, models
import epic.classes


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', epic.classes.CapitalizeField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='StatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', epic.classes.CapitalizeField(blank=True, max_length=25)),
            ],
        ),
    ]
