# Generated by Django 4.2.2 on 2023-06-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0002_statuscontract_statusevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
