# Generated by Django 4.2.2 on 2023-06-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0003_user_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
