# Generated by Django 4.2.2 on 2023-07-02 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import epic.classes


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0004_alter_user_date_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('company', epic.classes.CapitalizeField(max_length=255)),
                ('first_name', epic.classes.CapitalizeField(blank=True, max_length=25)),
                ('last_name', epic.classes.UppercaseField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('is_prospect', models.BooleanField(default=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('amount', models.IntegerField()),
                ('due_date', models.DateField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.client')),
                ('status_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.statuscontract')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='management_team',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sales_team',
        ),
        migrations.RemoveField(
            model_name='user',
            name='support_team',
        ),
        migrations.CreateModel(
            name='UserSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('attendees', models.IntegerField()),
                ('event_date', models.DateField()),
                ('notes', models.TextField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.contract')),
                ('status_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.statusevent')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='primary_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
