# Generated by Django 4.2.2 on 2023-07-02 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0005_client_contract_remove_user_management_team_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User (base)', 'verbose_name_plural': 'Users (base)'},
        ),
    ]
