# Generated by Django 4.2.2 on 2023-07-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': []},
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(to='epic.usermanagement'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
