# Generated by Django 4.2.2 on 2023-07-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0007_alter_event_options_event_event_name_event_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ManyToManyField(to='epic.usersales'),
        ),
        migrations.AddField(
            model_name='contract',
            name='user',
            field=models.ManyToManyField(to='epic.usersales'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(to='epic.usersupport'),
        ),
    ]
