# Generated by Django 4.2.2 on 2023-07-02 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0008_client_user_contract_user_alter_contract_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
    ]
