# Generated by Django 4.2.2 on 2023-07-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0009_rename_event_name_event_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['company']},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-due_date']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date']},
        ),
    ]
